### ISSUE TITLE
Room Types List of  admin in dashboard 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#201]
Room Types List in admin has added same room type .duplicacy issues That's why the hotel login master room inventory gets multiple entries of same room type.
<img width="1440" alt="Screen Shot 2022-09-27 at 4 27 53 PM" src="https://user-images.githubusercontent.com/85510636/192508146-067e15c8-05f8-4bc1-8e70-7a02f875b7c6.png">

**Comment by parveen-malik** [comment]
closed

**Comment by Rehachoudhary0** [comment]
Still not working pls check it @parveen-malik  sir

<img width="1440" alt="Screen Shot 2022-10-01 at 12 40 03 PM" src="https://user-images.githubusercontent.com/85510636/193397696-5e4e2031-4d9d-479d-bca5-20f975b68d22.png">
