### ISSUE TITLE
Error in /user/chat/sendMessage API when send message to Kitchen.

### ISSUE THREAD

**Issue by rvndsngwn** [Rehachoudhary0/hotel_testing#203]
https://app.roomistapp.com/api/user/chat/sendMessage

<img width="953" alt="Screenshot 2022-09-27 at 11 03 40 PM" src="https://user-images.githubusercontent.com/59143934/192596712-a9ba7029-bbb1-4629-8b5c-438b02995d69.png">

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/192756188-2ae14722-8025-4980-aea3-a3bb3b95960c.png)

**Comment by parveen-malik** [comment]
orio hotel: reception Works for chat ....but kichten doest not have firebase token

**Comment by parveen-malik** [comment]
we have to check crosscheck is it ui issue or any api issue.............firebase token why not generated some case ........reception get but kitchen did not get

**Comment by parveen-malik** [comment]
this is an operating buggs .............we should to know atleat one time login hotel kichen number ...............to get chat notification
