### ISSUE TITLE
Error format issue in /api/hotel/sendotp API 

### ISSUE THREAD

**Issue by rvndsngwn** [Rehachoudhary0/hotel_testing#204]
`👍 Expected behavior`

```
{
success: false,
error: ["Hotel Not Found"],
message:
"Pls Contact Admistrator For Registration !!!",
loggedIn: 0
}
```

`👎 Actual Behavior`

```
{
success: false,
error: "Hotel Not Found",
message:
"Pls Contact Admistrator For Registration !!!",
loggedIn: 0
}
```

<img width="953" alt="Screenshot 2022-09-27 at 11 41 14 PM" src="https://user-images.githubusercontent.com/59143934/192604369-f7de35be-a838-4e86-b538-a59a16efe792.png">

**Comment by parveen-malik** [comment]
is any issue pending in this api......

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/192751436-7e9eb08d-e0d5-4866-ba29-b7f78649ab9d.png)
