### ISSUE TITLE
🐛 Bug Report:  Room assign page of hotel  

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#208]
### 👟 Reproduction steps

I found this error on the room assign page. when I open the page to assign the room I got this without press any button.

### 👍 Expected behavior

it should error-free to assign a room to the traveler.

### 👎 Actual Behavior

![WhatsApp Image 2022-09-28 at 12 21 23 PM](https://user-images.githubusercontent.com/85510636/192709369-6f51ff97-d6d2-487f-ae3a-cae228c0c345.jpeg)

### 🎲 App version

Version 22.09.28+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
problem resolved from myend.........api and query recified with new scenerio............pls test  and let me know

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/192751241-10057ac1-c072-428d-a891-c33ed93dcfee.png)
