### ISSUE TITLE
🐛 Bug Report: Order detail page of hotel 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#209]
### 👟 Reproduction steps

When i tried to change the food status from hotel App ,after API calling  showing progress bar is loading only and this is not for limited time still happing. not able to update status of food .

### 👍 Expected behavior

Hotel should change the status of the food. 

### 👎 Actual Behavior

![WhatsApp Image 2022-09-28 at 1 22 09 PM](https://user-images.githubusercontent.com/85510636/192722643-94ac724e-2488-4958-ad0d-4af42180b308.jpeg)

### 🎲 App version

Version 22.09.28+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
The issue has been fixed in the next release, which you can test. @Rehachoudhary0

**Comment by parveen-malik** [comment]
is any help needed from myend in this api  arvind sir

**Comment by Rehachoudhary0** [comment]
okk @rvndsngwn
