### ISSUE TITLE
🐛 Bug Report: Hotel>Home and Kitchen  chat count showing wrong 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#211]
### 👟 Reproduction steps

Hotel chat count is not correct.

### 👍 Expected behavior

we want type-wise count in chat 

### 👎 Actual Behavior

![WhatsApp Image 2022-09-28 at 4 19 50 PM](https://user-images.githubusercontent.com/85510636/192766442-49fb1fd0-98f9-44c0-a43d-776f9964ec0d.jpeg)

### 🎲 App version

Version 22.09.28+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
Ok we will do later when free slot taken

**Comment by Rehachoudhary0** [comment]
thats why this is in low priority.

**Comment by Rehachoudhary0** [comment]
Still count is wrong .showimg 4 but there is 2 lins only one has been already seen by hotel so raimain one but showing 4 .


![Screenshot_20221005_164309](https://user-images.githubusercontent.com/85510636/194047823-e52a4293-3371-46b9-9c22-3121474a9c99.png)
![Screenshot_20221005_164324](https://user-images.githubusercontent.com/85510636/194047853-b5e1045d-e193-4788-abc7-8907f372faf0.png)

**Comment by parveen-malik** [comment]
already closed from api end...............let me know if any modification needed in api..........when possible @rvndsngwn

**Comment by rvndsngwn** [comment]
done
