### ISSUE TITLE
🐛 Bug Report: Admin app 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#212]
### 👟 Reproduction steps

Whenever we add a new hotel after the saving button. home page should be refresh.

### 👍 Expected behavior

the home page should be refresh.

### 👎 Actual Behavior

admin home refresh not working 

### 🎲 App version

Version 22.09.28+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
