### ISSUE TITLE
🐛 Bug Report: Hotel login

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#213]
### 👟 Reproduction steps

I found same time error in OTP screen whenever OTP is correct.

### 👍 Expected behavior

no error should be there.

### 👎 Actual Behavior

<img src="https://user-images.githubusercontent.com/85510636/192790197-32bcfca5-5906-4b49-aa51-45b93f34e1ef.jpeg" width=25% height=25% />

### 🎲 App version

Version 22.09.28+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
ui issue sir @rvndsngwn ....pls verify i am login using postman ...........first login as reception a=haut monte
![image](https://user-images.githubusercontent.com/62441016/192793391-44d0b15a-738c-4c62-acd6-1f4317e9a5bf.png)

**Comment by parveen-malik** [comment]
login with 9057238885  both 9057238855...........working
![image](https://user-images.githubusercontent.com/62441016/193025783-843d5206-665f-412f-9fa2-4da877dd8fd1.png)
![image](https://user-images.githubusercontent.com/62441016/193025927-4f460973-f961-47c6-a2f2-3ae95b7e5e3c.png)

**Comment by parveen-malik** [comment]
duplicate entery removed for while.............pls use same number again let me check any issue rise for meanwhile..............i am closing it............

**Comment by Rehachoudhary0** [comment]
okkk lemme check
