### ISSUE TITLE
🐛 Bug Report: Search hotel page 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#215]
### 👟 Reproduction steps

Showing top of the screen.

### 👍 Expected behavior

Search bar should be lil down .

### 👎 Actual Behavior

![WhatsApp Image 2022-09-28 at 6 32 32 PM-2](https://user-images.githubusercontent.com/85510636/192794171-a1d9b8d5-81a5-4d1c-9693-694725061b3f.jpeg)

### 🎲 App version

Version 22.09.28+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
