### ISSUE TITLE
🐛 Bug Report: Admin booking Dashboard 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#216]
### 👟 Reproduction steps

On this page, I can't see any booking of travelers. I booked three bookings by today.

### 👍 Expected behavior

Need to see all bookings for today.

### 👎 Actual Behavior

<img width="1440" alt="Screen Shot 2022-09-29 at 12 43 14 PM" src="https://user-images.githubusercontent.com/85510636/192966600-c7239d3c-899e-4a9d-8ebf-6b8ccf2c5d59.png">

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
for which hotel u booked..............u login as admin.......pls check prefer hotel

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/192967357-77aec9cc-8fb1-475e-8bf0-1281eb503fa2.png)
