### ISSUE TITLE
🐛 Bug Report: Hotel Dashboard Food order 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#218]
### 👟 Reproduction steps

In this page recently order showing on the downside of the page.

### 👍 Expected behavior

We want recent order on the front of the table.

### 👎 Actual Behavior

<img width="1440" alt="Screen Shot 2022-09-29 at 12 42 19 PM" src="https://user-images.githubusercontent.com/85510636/192966816-e41eeef3-ebb0-4779-a570-63bbed3853e9.png">

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
Ok no problem.
.I will do

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/193006313-b439bc5a-f1cc-4f55-a1f1-446dbc2bc24e.png)
