### ISSUE TITLE
🐛 Bug Report: Admin Food order list 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#219]
### 👟 Reproduction steps

Recent food order showing in the bottom of table.

### 👍 Expected behavior

Recent order should be in front of table.

### 👎 Actual Behavior

<img width="1440" alt="Screen Shot 2022-09-29 at 12 42 01 PM" src="https://user-images.githubusercontent.com/85510636/192969025-22c02561-3398-4883-b15d-42363ec16ee4.png">

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
both admin and hotel done
