### ISSUE TITLE
🐛 Bug Report: When Hotel has no data

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#220]
### 👟 Reproduction steps

When we search hotel for booking and  a hotel has no data, API shows the hotel as in the hotel list.

### 👍 Expected behavior

Whenever a hotel has no data then API doesn't need to show the hotel in the hotel list.

### 👎 Actual Behavior

When a hotel has no data, API shows the hotel as in the hotel list.

### 🎲 App version

Version 22.09.28+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
pls check it again i am removing ......duplicate hotel
