### ISSUE TITLE
🐛 Bug Report: User food cart page

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#222]
### 👟 Reproduction steps

when I am going to type reviews,the place order button showing misplace behaviour .

### 👍 Expected behavior

Top of the keyboard this button should not be showing I think 

### 👎 Actual Behavior

![WhatsApp Image 2022-09-29 at 7 14 29 PM](https://user-images.githubusercontent.com/85510636/193050944-5ab34b84-32ea-4898-a8d2-1a978ce9ac96.jpeg)

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
