### ISSUE TITLE
🐛 Bug Report: User kitchen page 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#224]
### 👟 Reproduction steps

User kitchen page chat showing as hotel .

### 👍 Expected behavior

Should be as user 

### 👎 Actual Behavior

![WhatsApp Image 2022-09-29 at 7 14 30 PM](https://user-images.githubusercontent.com/85510636/193052389-bef158e0-ba91-4d7b-8bfe-8f449360fa6f.jpeg)

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
400 Bad Request error in /api/user/chat/read 

@parveen-malik @Rehachoudhary0 

![Screenshot 2022-10-01 at 2 10 51 AM](https://user-images.githubusercontent.com/59143934/193353369-ea83ee18-1b61-438c-8822-17549875562c.png)

**Comment by parveen-malik** [comment]
this is an validation error this error due to becuase of `hotel_user_id`='24' not available in database

**Comment by rvndsngwn** [comment]
Sir where can I find hotel_user_id??

**Comment by parveen-malik** [comment]
api improveement done............dependency from cache to get hotel user id ............removed and impelementation of all hotel user id related to hotel passe as an object.............api work done

**Comment by parveen-malik** [comment]
@rvndsngwn will apply things in ui...........next release of ui

**Comment by rvndsngwn** [comment]
done
