### ISSUE TITLE
🐛 Bug Report: Hotel Checkin page 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#226]
### 👟 Reproduction steps

I think there is a need for validation in input text because zero is not countable for a person.

### 👍 Expected behavior

Input should be more than zero input ,invalid input .

### 👎 Actual Behavior

![Screenshot_20220929_184827](https://user-images.githubusercontent.com/85510636/193054677-484f263b-4044-4bb1-b76f-22164b937236.png)

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
