### ISSUE TITLE
🐛 Bug Report:Hotel Checkout page

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#227]
### 👟 Reproduction steps

Need to refresh on checkout notification.

### 👍 Expected behavior

Should be refresh same time.

### 👎 Actual Behavior

![Screenshot_20220929_190659](https://user-images.githubusercontent.com/85510636/193395699-d50ca8fc-97bf-41e6-819b-431d5c5093f5.png)

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Could you please provide me with more information?

**Comment by rvndsngwn** [comment]
There's something wrong here

**Comment by rvndsngwn** [comment]
done
