### ISSUE TITLE
🐛 Bug Report: Hotel Identity and room page

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#228]
### 👟 Reproduction steps

There is no hint to fill in first identity information.

### 👍 Expected behavior

I think need to show the first identity as we discuss previous or show same popup  to understand what to do first 

### 👎 Actual Behavior

![Uploading Screenshot_20220929_190258.png…]()

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
