### ISSUE TITLE
🐛 Bug Report: Hotel New check_in  

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#229]
### 👟 Reproduction steps

New check_in list is ovetlap .

### 👍 Expected behavior

Need to maintain the gape between all.

### 👎 Actual Behavior

![Screenshot_20220929_190128](https://user-images.githubusercontent.com/85510636/193056734-b3ad4e0a-3347-468f-84cf-96b4d01b8b31.png)

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
