### ISSUE TITLE
🐛 Bug Report: The image gets null when creating a new hotel in the app from the admin.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#230]
### 👟 Reproduction steps

when I creat a hotel by the app.I fill the all details and image of the hotel but this is not showing on the hotel login profile page I need to update the image from dashboard.

### 👍 Expected behavior

Hotel image fill by admin app should be visible in hotel app .

### 👎 Actual Behavior

Image not showing in hotel app if I filled this by admin app.

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
/hotel/hotelsListApi
/hotel/addNew

**Comment by rvndsngwn** [comment]
There was an error in the front-end, which I have fixed.

**Comment by rvndsngwn** [comment]
The front-end error was fixed, but the API error remained. This needs to be checked, @parveen-malik sir.

**Comment by rvndsngwn** [comment]
https://app.roomistapp.com/api/hotel/addNew

`Request body`
![Screenshot 2022-10-01 at 4 16 50 AM](https://user-images.githubusercontent.com/59143934/193366280-39421737-73b7-491d-b5c3-8d7b9d884a5a.png)

`Response` of /hotel/hotelsListApi
![Screenshot 2022-10-01 at 4 18 13 AM](https://user-images.githubusercontent.com/59143934/193366370-39b58990-1a5d-483a-a525-167402a827c9.png)

**Comment by parveen-malik** [comment]
ok i will fix......let me know when @rvndsngwn sir you are available.........

**Comment by parveen-malik** [comment]
fixed from myend ..........pls check

**Comment by Rehachoudhary0** [comment]
not working still

**Comment by parveen-malik** [comment]
already fixed frommy end  @rvndsngwn will close it .......

**Comment by rvndsngwn** [comment]
done
