### ISSUE TITLE
🐛 Bug Report: User Check-In notification 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#231]
### 👟 Reproduction steps

Auto refreshes not working on fireball notification in traveler on check-In. i need to refresh the app for getting data some time not very slot.

### 👍 Expected behavior

Auto refresh on fireball notification in traveler in checkin.

### 👎 Actual Behavior

Auto refresh not working on fireball notification in traveler on check-In.

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
There's something wrong here

**Comment by rvndsngwn** [comment]
Scroll to refresh added
