### ISSUE TITLE
🐛 Bug Report: cache control  => time limit in response headers.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#232]
### 👟 Reproduction steps

Expire login time have to increase in API only.

### 👍 Expected behavior

Expire login time have to increase in API only.

### 👎 Actual Behavior

Not working this right now.

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
ok we fix today when all issue fixed

**Comment by parveen-malik** [comment]
@rvndsngwn confirm that without it we didnot any issue .......we will resolve later.......
