### ISSUE TITLE
🚀 Feature: Admin profile Edit rights

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#233]
### 🔖 Feature description

Admin has right to  edit profile details 

### 🎤 Pitch

We need the feature because same time needs to edit the profile of the admin so if there is no feature then how to edit details?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
we will do that On permision of @hemantsoftwarexprts hemant sir ............if this feature needed..............when you can reopen this issue i will colse it for while............

**Comment by Rehachoudhary0** [comment]
this is a feature, not a bug so there is no need to close it ..because this is not completed so we need to complete it further whenever we want ..
