### ISSUE TITLE
🐛 Bug Report: Dashboard Admin switch hotel

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#234]
### 👟 Reproduction steps

Dashboard Admin not able to switch other hotel if they have multiple hotels  .

### 👍 Expected behavior

Admin should switch multiple hotels if admin wants.

### 👎 Actual Behavior

not working according to admin.

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
working on it

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/193278954-8ba49d52-7acb-4a46-b5c6-daa9e2bfb501.png)
