### ISSUE TITLE
📚 Documentation: App Switch hotel 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#235]
### 💭 Description

If App needs to switch hotel API modification then we will do further.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
api work to modify ...........an switching functionality Modified done...incase app need an admin access to switch an admin different hotel and after that admin role also .......maintain to do further swithing ...........and hotel owner have mulitple receptions or property with same owner number.............he or she also would able to that......................from myend its apply but postman testing not possible...............if we need it in app.......we hopefully not getting any issue
