### ISSUE TITLE
🐛 Bug Report: Dashboard home Tab 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#236]
### 👟 Reproduction steps

whenever I click on the dashboard home page tab (such as total order) that will respond as logout tab.

### 👍 Expected behavior

All tabs should show responses according to the tab name.

### 👎 Actual Behavior

The home page tab will respond as logout tab.

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
on clicking i am logout![image](https://user-images.githubusercontent.com/62441016/193399314-d568db8d-198a-49f8-a960-84652fdce6fe.png)

**Comment by parveen-malik** [comment]
pls show me this issue on anydesk

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/193405988-87d603fb-8ceb-486c-b6df-004594f03564.png)
@secoundery user order in listing fixed............on edit working

**Comment by parveen-malik** [comment]
done.......and verify
