### ISSUE TITLE
🐛 Bug Report:  Dashboard properties visibility

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#237]
### 👟 Reproduction steps

multiple properties visible basis on phone number registered either in owner, reception, or kitchen any where in the data base, will be visible to hotel login in switch area.

### 👍 Expected behavior

multiple properties visible basis on phone number registered either in owner, reception, or kitchen any where in the data base, will be visible to hotel login in switch area.

### 👎 Actual Behavior

Just admin get all hotel but not reception , owner and kitchen.

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
previousely it checks phone number have available With Multiple Property As Owner able to Access ........all property Like All branches of hotel.................it means modified scenerio is to check current phone number ............may be as owner number , reception number, kithcen ...............all able to see all property or branches or all recption once..................no issue ...............i am working on it

**Comment by parveen-malik** [comment]
previous kichen would able to do that access to other property

![image](https://user-images.githubusercontent.com/62441016/193287808-708d820f-0099-4585-87bc-4f3f8a85609b.png)

**Comment by parveen-malik** [comment]
done pls check![image](https://user-images.githubusercontent.com/62441016/193288099-ef35aa86-0db2-4241-9af2-85830fe04a5c.png)

**Comment by Rehachoudhary0** [comment]
this is working fine for the reception but I am not able to check in the owner number because there is an 
<img width="1440" alt="Screen Shot 2022-10-01 at 11 33 11 AM" src="https://user-images.githubusercontent.com/85510636/193395263-7d354fad-f595-409e-9639-0fffebcaf3fa.png">
<img width="1440" alt="Screen Shot 2022-10-01 at 11 33 25 AM" src="https://user-images.githubusercontent.com/85510636/193395267-226d251e-58e7-4ff2-9835-156782f1ad08.png">
error when login. reception login is fine but owner login is not fine .

**Comment by parveen-malik** [comment]
this issue not relted to hotel switching..............pls add another feture functuinality new Function To Make An Hotel Login ....................Because Previous Concept Only Add Two Number reception_number,kichen number................added to hotel Login.............
new hotel registeration process from Both api as well As web dashboard
