### ISSUE TITLE
🐛 Bug Report: Food menu image not loaded from API

### ISSUE THREAD

**Issue by rvndsngwn** [Rehachoudhary0/hotel_testing#238]
### 👟 Reproduction steps

Images of the food menu do not load when the API returns the image URL.

https://app.roomistapp.com/api/user/foodMenuList

@parveen-malik @heman4t @sanjubhita 

### 👍 Expected behavior

Images successfully loaded.

### 👎 Actual Behavior

Error: Connection timed out.

https://test.mohesu.org/public/foodImages/1639480618_coconut-rice-recipe-500x500.jpg

![Screenshot 2022-10-01 at 2 26 53 AM](https://user-images.githubusercontent.com/59143934/193355363-cc0c7aca-f797-4f35-b8e3-e206c2c27796.png)

### 🎲 App version

Version 22.09.29+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
done
