### ISSUE TITLE
🐛 Bug Report: Hotel Recent chat text 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#240]
### 👟 Reproduction steps

 Recent chat doesn't show in the list of chat page  …same as on the home page of  and the  count of chat showing 4 Don’t know how. recent msg is hey hotel not clean ....

![Screenshot_20221001_131553](https://user-images.githubusercontent.com/85510636/193400262-61310576-4ecf-493d-94df-580bedaa822a.png)

![Screenshot_20221001_131517](https://user-images.githubusercontent.com/85510636/193400310-c58a0ff5-d5d4-43a2-aa4e-532b26697a12.png)

### 👍 Expected behavior

Recent chat should be on top in the list of chat at hone or list chat 

### 👎 Actual Behavior

.

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
api improvement @rvndsngwn will ui improvement

**Comment by rvndsngwn** [comment]
message received from API `/api/hotel/chat/latest`

**Comment by rvndsngwn** [comment]
<img width="543" alt="Screenshot 2022-10-05 at 1 37 33 AM" src="https://user-images.githubusercontent.com/59143934/193915920-9f373a01-f02a-4d87-ad16-5ad15aa74764.png">

**Comment by rvndsngwn** [comment]
HI @parveen-malik sir kindly check this issue.
https://app.roomistapp.com/api/hotel/chat/latest

In latest chat API `message` attribute gets wrong value.

<img width="583" alt="Screenshot 2022-10-08 at 11 46 56 PM" src="https://user-images.githubusercontent.com/59143934/194722214-3651caf9-d64f-4aa1-9cd5-2b9c7c81d61f.png">
