### ISSUE TITLE
🚀 Feature: Hotel ,traveler and kitchen has remark filed . 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#242]
### 🔖 Feature description

We get remarks from users when users going to order food but we don't show this anywhere in traveler kitchens and hotels..

### 🎤 Pitch

 I think this is important to show what is the remark of the food.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
