### ISSUE TITLE
🐛 Bug Report: Secondry user food order in Hotel and kitchen 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#244]
### 👟 Reproduction steps

when I order the food from a secondary user I will get nill values.

### 👍 Expected behavior

we have to use information of secondary user .

### 👎 Actual Behavior

![Screenshot_20221001_161123](https://user-images.githubusercontent.com/85510636/193405753-6c0def40-6b3e-4ab9-9481-648a4847075a.png)

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
from myside api improved.........ui fixed @rvndsngwn will do

**Comment by rvndsngwn** [comment]
@parveen-malik sir plz look into #254

**Comment by rvndsngwn** [comment]
Room no getting null in `/hotel/order/listHotel` API

**Comment by rvndsngwn** [comment]
done
