### ISSUE TITLE
🐛 Bug Report: Kitchen home page 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#245]
### 👟 Reproduction steps

I am not able to see the home page progress bar showing.

### 👍 Expected behavior

we need to show home page accordingly ....

### 👎 Actual Behavior

![Screenshot_20221001_161054](https://user-images.githubusercontent.com/85510636/193405800-896e123b-92c1-491d-929a-30b3b9b85734.png)

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
