### ISSUE TITLE
🐛 Bug Report: Dashbord Dashboard

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#246]
### 👟 Reproduction steps

this is working fine for the reception but I am not able to check in the owner number because there is an error when login. reception login is fine but owner login is not fine.

### 👍 Expected behavior

this is should be login as owner .

### 👎 Actual Behavior

<img width="1440" alt="Screen Shot 2022-10-01 at 11 33 11 AM" src="https://user-images.githubusercontent.com/85510636/193406315-e3e8747f-960a-464b-afef-9122683db77b.png">
<img width="1440" alt="Screen Shot 2022-10-01 at 11 33 25 AM" src="https://user-images.githubusercontent.com/85510636/193406316-bad907c4-13a0-4314-bd79-735406b5c9bf.png">

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
this is not an bugg............new feature implementation needed for it....................we have to make owner number login............currentely receptiona and kitchen available
