### ISSUE TITLE
🐛 Bug Report: User chat page 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#247]
### 👟 Reproduction steps

 Second user chat showing as the first user chats with the first user name and if the first user doing a chat that chats shows as the second user with the second user name.Reception of user sending text as a hotel. Same as a kitchen if hotel replies on that chat after that showing correct.

### 👍 Expected behavior

should be correct 

### 👎 Actual Behavior

![WhatsApp Image 2022-10-01 at 4 31 33 PM](https://user-images.githubusercontent.com/85510636/193406610-ba272130-5ae2-4291-92a5-c74b42ddeb2e.jpeg)

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
