### ISSUE TITLE
🐛 Bug Report: In dashboard admin food order list

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#248]
### 👟 Reproduction steps

when a secondary user places the food order from app, in the admin that food shows nil value on the name of user . that problem has been occurred on order views and listing page .

### 👍 Expected behavior

should be show correctly with needed information of secondary user 

### 👎 Actual Behavior

not showing needed info.

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/193407101-85519017-a9de-48b4-acbb-7257e9093125.png)
order list

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/193407152-e9f92064-548a-4b2a-9a57-8bf35ec567da.png)
