### ISSUE TITLE
🐛 Bug Report: Fiirebase  notification not clickable .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#250]
### 👟 Reproduction steps

when I click on chat notification or food I am not able to click on that.

### 👍 Expected behavior

Firebase notification has to be clickable for all apps according to notification open page 

### 👎 Actual Behavior

.

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
improved
