### ISSUE TITLE
🐛 Bug Report: Admin should have QR code in bottom of page 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#252]
### 👟 Reproduction steps

Admin should have QR code in bottom of page.

### 👍 Expected behavior

.

### 👎 Actual Behavior

there is no QR code.
![Screenshot_20221001_185211](https://user-images.githubusercontent.com/85510636/193412540-fb9f137a-b1e4-49e1-bb3a-c7373d35985d.png)

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
