### ISSUE TITLE
🐛 Bug Report: location_id attribute getting in a string instead of JSON in api/hotel/order/list Hotel API

### ISSUE THREAD

**Issue by rvndsngwn** [Rehachoudhary0/hotel_testing#254]
### 👟 Reproduction steps

In api/hotel/order/list API, location_id attribute format is Json but in response location id is getting in string.

### 👍 Expected behavior

```
"location_ip": {
          "log": "77.0989086",
          "lat": "28.6370394"
        },
```

### 👎 Actual Behavior

```
"location_ip": "{"log": "00.00000, 00.00000","lat": "00.00000, 00.00000"}",
```

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
{
    "success": true,
    "error": [],
    "message": "Hotel : Orio peace of beauty , foodOrders List ",
    "loggedIn": 1,
    "response": {
        "foodOrdersCount": 4,
        "foodOrdersList": [
            {
                "food_order_id": 18,
                "hotel_id": 4,
                "customer_id": 15,
                "name": "The second",
                "type": "secondary",
                "primary_id": 9,
                "location_ip": "{\"log\": \"76.4648377\",\"lat\": \"29.146752\"}",
                "food_order_items": [                    
                ]
            },
            {
                "food_order_id": 17,
                "hotel_id": 4,
                "customer_id": 15,
                "name": "The second",
                "location_ip": "{\"log\": \"76.4648377\",\"lat\": \"29.146752\"}",
                "food_order_items": [
                ]
            },
            {
                "food_order_id": 16,
                "hotel_id": 4,
                "customer_id": 8,
                "name": "Virgil funky",
                "type": "primary",
                "primary_id": null,
                "location_ip": "{\"log\": \"00.00000, 00.00000\",\"lat\": \"00.00000, 00.00000\"}",
                "food_order_items": [
                ]
            },
            {
                "food_order_id": 15,
                "hotel_id": 4,
                "customer_id": 8,
                "name": "Virgil funky",
                "type": "primary",
                "location_ip": "{\"log\": \"00.00000, 00.00000\",\"lat\": \"00.00000, 00.00000\"}",
                "food_order_items": [
                ]
            }
        ]
    }
}

**Comment by parveen-malik** [comment]
sir ji iss response ko dekh kar mujhey suggest karey ..........mujhey yeh issue google place api kaa lagg rhaa

**Comment by parveen-malik** [comment]
solved.............
