### ISSUE TITLE
🐛 Bug Report: Hotel >chat count not working for secondary user

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#256]
### 👟 Reproduction steps

In hotel, chat count of user not able to show .

### 👍 Expected behavior

Need to show chat count of secondary user in hotel no kitchen. 

### 👎 Actual Behavior

Not working chat count in hotel and kitchen.

### 🎲 App version

Version 22.10.01+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
its done pls verify @Rehachoudhary0

**Comment by parveen-malik** [comment]
verified by @rvndsngwn @Rehachoudhary0
