### ISSUE TITLE
🐛 Bug Report: At Hotel booking showing new hotel has 1 star .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#259]
### 👟 Reproduction steps

when we are going to book hotel there is new hotel rating showing 1 .

### 👍 Expected behavior

If there is a new hotel or the hotel has no rating then don't show the rating. This is showing bad request.

### 👎 Actual Behavior

.

### 🎲 App version

Version 22.10.05+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
