### ISSUE TITLE
🚀 Feature Hotel and User >home icons .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#260]
### 🔖 Feature description

Whenever a user has no hotel access and a hotel has no user checked_in so why we showing null values page on home page like food list page .

### 🎤 Pitch

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
description not understanding.
