### ISSUE TITLE
🚀 Feature: Hotel>checking info page > identity and room buttons 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#261]
### 🔖 Feature description

 Chekig_in info page has an identity and room button should be hide before fill adult, bags and adult info. 

### 🎤 Pitch

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
