### ISSUE TITLE
🐛 Bug Report:  User> profile validation issues .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#262]
### 👟 Reproduction steps

when I use the same user's email id with another user this is showing something went wrong not showing a validation error in edit text filed. how to user find what is wrong.

### 👍 Expected behavior

proper validation showing in text fields in whole APP pls check all fields of APP.

### 👎 Actual Behavior

![WhatsApp Image 2022-10-05 at 6 42 02 PM](https://user-images.githubusercontent.com/85510636/194069761-24e951f3-2b24-47ef-8ea0-b9fb8018e2dd.jpeg)

### 🎲 App version

Version 22.10.05+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
