### ISSUE TITLE
🐛 Bug Report: User Chat Screen format not correct 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#263]
### 👟 Reproduction steps

hotel reply to primary user but in user chat showing hotel text in right side as user .

### 👍 Expected behavior

should be accordigly 

### 👎 Actual Behavior

![WhatsApp Image 2022-10-05 at 6 42 02 PM (1)](https://user-images.githubusercontent.com/85510636/194070243-9b24cafc-e207-452a-837a-609e9b731fc8.jpeg)

### 🎲 App version

Version 22.10.05+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
