### ISSUE TITLE
🐛 Bug Report: Hotel >chat firebase notification doesn't refresh the chat page .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#265]
### 👟 Reproduction steps

when we are going to chat with the hotel, the hotel gets a notification but on the notification, there is no refresh data. I had to pull the screen to refresh even though the hotel page not showing any new chat.

### 👍 Expected behavior

it should refresh data according to the notification ..

### 👎 Actual Behavior

Not getting any new data on notification.

### 🎲 App version

Version 22.10.05+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
