### ISSUE TITLE
🐛 Bug Report: Food and chat notifications were not sent to the second user.

### ISSUE THREAD

**Issue by rvndsngwn** [Rehachoudhary0/hotel_testing#266]
### 👟 Reproduction steps

When I testing second user notifications about food order and chat.

### 👍 Expected behavior

Food and chat notifications were successfully sent to the second user.

### 👎 Actual Behavior

Food and chat notifications were not sent to the second user.

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
no issue let me konw when getting time.......we will fix it

**Comment by parveen-malik** [comment]
from myside its done @rvndsngwn pls verify

**Comment by parveen-malik** [comment]
only food order ....done

**Comment by parveen-malik** [comment]
done ...and verified notification show verified withh hemant sir.....but chat and ffod order not shown in related user login dashboard of app...

**Comment by parveen-malik** [comment]
@rvndsngwn  ui issue  or api mofification needed 
????
