### ISSUE TITLE
🐛 Bug Report: In the Hotel and Kitchen, Notification response is the same for primary and secondary users.

### ISSUE THREAD

**Issue by rvndsngwn** [Rehachoudhary0/hotel_testing#267]
### 👟 Reproduction steps

When I testing notifications in the app.

### 👍 Expected behavior

In the Hotel and Kitchen, Notification response is the some difference between the primary and secondary users.

### 👎 Actual Behavior

In the Hotel and Kitchen, Notification response is the same for primary and secondary users.

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
no issue sir...when ur available we will do @rvndsngwn
