### ISSUE TITLE
🐛 Bug Report: Hotel / Kitchen home chat of primary and secondary user showing null name

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#268]
### 👟 Reproduction steps

Hotel chat showing null value .

### 👍 Expected behavior

Has to be get values of user .

### 👎 Actual Behavior

![Screenshot_20221010_111737](https://user-images.githubusercontent.com/85510636/194805012-f4a38c6a-cdbc-4897-a107-89d23f052fee.png)

![WhatsApp Image 2022-10-10 at 5 57 23 PM](https://user-images.githubusercontent.com/85510636/194867025-9a062b1b-5490-4e34-9233-eebbced6905f.jpeg)

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done

**Comment by Rehachoudhary0** [comment]
STILL pending ....
![WhatsApp Image 2022-10-19 at 3 40 20 PM](https://user-images.githubusercontent.com/85510636/196663030-367ae81a-dc9e-46d5-9038-acc9fd11df77.jpeg)
