### ISSUE TITLE
🐛 Bug Report: Hotel booking check-in and checkout time and date is totally wrong with notification token not available

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#271]
### 👟 Reproduction steps

 when i am going book hotel then automatically hotel picks up the date as yesterday (09 Oct to 10 Oct)and after that, this is showing unexpected results like check-in time is 9-OCT 12PM and checkout time is 9-OCT 11AM (same Date)and night is zero .pls look the SS. Showing notification token not available. 

### 👍 Expected behavior

The calendar is restricted to picking the date before TODAY. we must hide the date before today and must have to pick the current date by default after that user change the date accordingly.

### 👎 Actual Behavior

![Screenshot_20221010_130801](https://user-images.githubusercontent.com/85510636/194819366-5cd557ab-2976-4b7c-9188-516a53c22215.png)
![Screenshot_20221010_132028](https://user-images.githubusercontent.com/85510636/194820161-f8614caa-b8dd-4e98-965f-ed8ff88e2629.png)

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
In real device working well
