### ISSUE TITLE
🐛 Bug Report: user get firebase notification of food status on this needs to be auto udate in user API.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#273]
### 👟 Reproduction steps

when hotel going to deliver order in user there is no auto-update status on firebase notification . 

### 👍 Expected behavior

it has to be an auto-update feature for food status.

### 👎 Actual Behavior

not auto update working .

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
In notification response: click_action have dynamic value.

@parveen-malik @Rehachoudhary0

**Comment by parveen-malik** [comment]
done sir
