### ISSUE TITLE
🐛 Bug Report: Kitchen dones't get notification of food from primary and secondary user.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#276]
### 👟 Reproduction steps

When i am going to order food then Kitchen doesn't get notification of food from the primary and secondary users. I had to reopen the appp for showing list of food .

### 👍 Expected behavior

Kitchen need to get push notification from both users 

### 👎 Actual Behavior

not working ....

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done

**Comment by Rehachoudhary0** [comment]
still not working

**Comment by Rehachoudhary0** [comment]
when APP is close then we get push notifications but when app is open we don't get notification .

**Comment by rvndsngwn** [comment]
done
