### ISSUE TITLE
🐛 Bug Report: User review of food page UI is not good need to review

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#277]
### 👟 Reproduction steps

If there is no remark then pls not need to show the field of reviews and the review's bottom shit text size is too big pls set the font size according to page.

### 👍 Expected behavior

Need to fix it accordingly .

### 👎 Actual Behavior

![WhatsApp Image 2022-10-10 at 7 19 25 PM](https://user-images.githubusercontent.com/85510636/194881806-c62b3054-7242-4293-a0fe-aab7cb5fee27.jpeg)

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
