### ISSUE TITLE
🐛 Bug Report:  After user food reviews need to refresh the page even back to page .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#278]
### 👟 Reproduction steps

When the user is going to review the food then after reviews ned to refresh the page.

### 👍 Expected behavior

Need to refresh the page .

### 👎 Actual Behavior

![WhatsApp Image 2022-10-10 at 7 19 24 PM](https://user-images.githubusercontent.com/85510636/194882938-1f596f8e-7103-4911-a260-82bd50f6c017.jpeg)

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
