### ISSUE TITLE
🐛 Bug Report: Hotel room page user info list ui is not good 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#279]
### 👟 Reproduction steps

The list user ui is showing green text in both lines .. the last one is green is ok but the user name mut be in black accordingly UI  and the user room number has to shift in right side .... all three is in same line is not looking good .

### 👍 Expected behavior

As I texted instructions in above.

### 👎 Actual Behavior

![WhatsApp Image 2022-10-10 at 5 57 27 PM](https://user-images.githubusercontent.com/85510636/194883190-2a1d3a5e-51b2-4501-8b86-13ca7d2ca6d5.jpeg)

### 🎲 App version

Version 22.10.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Done
