### ISSUE TITLE
🐛 Bug Report: Dashboard food image too much large then error 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#280]
### 👟 Reproduction steps

when the image is too large its showing an error page no validation or something else notification .

### 👍 Expected behavior

it shows validation  error like this image is too much big .

### 👎 Actual Behavior

<img width="1440" alt="Screen Shot 2022-10-11 at 11 37 00 AM" src="https://user-images.githubusercontent.com/85510636/195019563-9adb82b5-cd2c-4173-b627-349c7a35770c.png">

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
validation recityfy and welll tested by @Rehachoudhary0 ...donee
