### ISSUE TITLE
🐛 Bug Report: Cancel booking not showing in backoffice.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#283]
### 👟 Reproduction steps

Cancel booking not showing in backoffice.

### 👍 Expected behavior

Cancel booking should be in back office.

### 👎 Actual Behavior

.

### 🎲 App version

Different version (specify in environment)

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
Ok I will do that ...

**Comment by parveen-malik** [comment]
admin would able to filter all booking cancel Or Fresh..............done
