### ISSUE TITLE
🐛 Bug Report:  Hotel booking >In particular location of hotel searching shows other location hotel .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#285]
### 👟 Reproduction steps

when I searched the hotel for to Delhi location but this is showing mussoori hotel .

### 👍 Expected behavior

The data of Delhi location should be shown only of Delhi and not the data of other location should be shown anywhere else.

### 👎 Actual Behavior

![WhatsApp Image 2022-10-19 at 1 08 56 PM](https://user-images.githubusercontent.com/85510636/196638228-45fcf881-037d-494c-9ce5-df51ecbe063d.jpeg)

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
new delhi p ek hotel h ...orio only

**Comment by parveen-malik** [comment]
for Better Results.........we removed Hotel Update Older fields like landmark or postal ,subordinate...when using google place api in web dashboard............app ui points....i think we did not gett any old field existence when sending response of google api to our api to add and update an hotel....@arvind will take
