### ISSUE TITLE
🐛 Bug Report: Tablet views > Kitchen and Hotel > remark must be removed when a user doesn't give any remark with food ordering.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#286]
### 👟 Reproduction steps

in tab views UI not looks good.the total number tab is not full on screen this is should be full left to right corner . when the user did not give a remark to the user for food then why we are showing a null remark filed here .this must be removed when a user doesn't give any remark with food ordering.

### 👍 Expected behavior

should be right accordingly.

### 👎 Actual Behavior

![Screenshot_20221019_133537](https://user-images.githubusercontent.com/85510636/196669055-f3505be4-07d6-49b7-915e-34695a3270b9.png)

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
order new api store remark request as it is in dadtabase............arvind ji pls check order new ui screen before sent to api if any condition placed in ui frontend

**Comment by rvndsngwn** [comment]
done

**Comment by Rehachoudhary0** [comment]
Still you are sending remark null string in to request .
<img width="1440" alt="Screen Shot 2022-11-08 at 12 12 46 PM" src="https://user-images.githubusercontent.com/85510636/200493447-8608d135-7105-4f1b-adc5-7ec534bd3b41.png">
