### ISSUE TITLE
🐛 Bug Report: Hotel App >Food Order delivered data  list not showing in app 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#289]
### 👟 Reproduction steps

when hotel going to update food order after that that is not showing in list of hotel but user has seen all type of orders status list of food .

### 👍 Expected behavior

all type of food list status has to be shows in hotel app . 

### 👎 Actual Behavior

![Screenshot_20221020_180559](https://user-images.githubusercontent.com/85510636/196953231-d01a92a1-6021-4018-aa7b-7785d31d99df.png)
![WhatsApp Image 2022-10-20 at 6 08 40 PM](https://user-images.githubusercontent.com/85510636/196953442-1e777c9d-ac32-462e-820d-fba93c341f62.jpeg)

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
