### ISSUE TITLE
🐛 Bug Report: user App>modify booking showing something wrong error.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#290]
### 👟 Reproduction steps

when i am going to modify booking its showing something wrong in app .

### 👍 Expected behavior

should be working fine .

### 👎 Actual Behavior

![WhatsApp Image 2022-10-21 at 4 50 52 PM](https://user-images.githubusercontent.com/85510636/197185179-274c62d6-01fe-4f42-9058-35927d6f9df9.jpeg)

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
This doesn't seem right, invalid
