### ISSUE TITLE
🐛 Bug Report: Booking convert in to checked-in after that user has access to cancel and modify the booking .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#291]
### 👟 Reproduction steps

When Booking converts into checking after that we cancel the booking but I think this is not good .before checking show this option only. We can’t identify booking is converted to check in or not .

### 👍 Expected behavior

  I think after check-in user doesn't have access to modify and cancel the booking .

### 👎 Actual Behavior

![Screenshot_20221021_164918](https://user-images.githubusercontent.com/85510636/197186539-048c61b1-72b6-4293-883f-9571dfc5e44a.png)

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
