### ISSUE TITLE
🐛 Bug Report: In hotel app > Notification API is not working 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#292]
### 👟 Reproduction steps

The notification API is not working.when hotel  has notification and hasn't have,in both condition . there is no fix number this is common for all hotel

### 👍 Expected behavior

notification API  should be working fine.

### 👎 Actual Behavior

![Screenshot_20221021_174419](https://user-images.githubusercontent.com/85510636/197193322-fde33f88-7cc2-4fe4-83dd-c0c2c2e6b311.png)

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done

**Comment by parveen-malik** [comment]
sir this issue seen in hotel :9022222222

**Comment by rvndsngwn** [comment]
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-02 at 09 49 50](https://user-images.githubusercontent.com/59143934/199394936-2c3a056e-1444-46d0-8523-2fa2abf8c08c.png)
