### ISSUE TITLE
🐛 Bug Report: New hotel  booking hotel notification.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#293]
### 👟 Reproduction steps

New hotel  booking shows to hotel push notification numeric numbers (user id )only not showing the name of user.

### 👍 Expected behavior

should be show customer number also .

### 👎 Actual Behavior
![WhatsApp Image 2022-10-31 at 5 17 22 PM (1)](https://user-images.githubusercontent.com/85510636/199001780-2d73d619-d5c5-489e-8ad1-f97d4c4c5117.jpeg)

.

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
format applied 
![WhatsApp Image 2022-11-01 at 7 38 05 PM](https://user-images.githubusercontent.com/62441016/199254367-1a16a5e3-1d7c-40de-91c4-0d3da63346c2.jpeg)

**Comment by parveen-malik** [comment]
done pls check and verify
