### ISSUE TITLE
🐛 Bug Report: Hotel Check-in request  notification wrong .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#294]
### 👟 Reproduction steps

when i was send user (xpensive user )request to check-in ,request has shown name like  (user name )not the actually name of user . 

### 👍 Expected behavior

should show the actual user NAME. 

### 👎 Actual Behavior
![WhatsApp Image 2022-10-31 at 5 17 22 PM](https://user-images.githubusercontent.com/85510636/199001666-3cbcbdcc-9118-40fe-91ac-51490357fa79.jpeg)

.

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
from customer name is set.......but ui show static pls make chane in ui

**Comment by Rehachoudhary0** [comment]
In notification API shows right but not in push up .... backend is correctly working I think that is from frond end @rvndsngwn pls check this.

![Screenshot_20221101_232143](https://user-images.githubusercontent.com/85510636/199303460-bce0fac9-df2f-4b10-90b1-5c83fc4640c6.png)

**Comment by rvndsngwn** [comment]
done
