### ISSUE TITLE
🐛 Bug Report: Hotel home page not showing food order .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#297]
### 👟 Reproduction steps

No auto-refresh on food order in the hotel .food order not shows on the home page of hotel.

### 👍 Expected behavior

should be auto refresh .

### 👎 Actual Behavior

.

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
