### ISSUE TITLE
🐛 Bug Report: User home page not getting refresh on food status notification.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#298]
### 👟 Reproduction steps

 User food update notification could not refresh the status of food at home page.

### 👍 Expected behavior

should be refresh .

### 👎 Actual Behavior

.

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
