### ISSUE TITLE
🐛 Bug Report: Primary and secondary user notification clickable issues

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#299]
### 👟 Reproduction steps

first user get second user notification but this is not clickable. 
second user get first user notification but this is not clickable. 

### 👍 Expected behavior

both should be clickable. 

### 👎 Actual Behavior

.

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done
