### ISSUE TITLE
🐛 Bug Report: when same user or hotel login in another device first device is not logged out 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#301]
### 👟 Reproduction steps

when i login in another device with the same user or hotel or kitchen ,first device is not logged out both are working in same time .

### 👍 Expected behavior

when one user is logged in with one device and the same user log in with another also then first one has to be logout .

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all number 

### 📲 User Type

Other

### 🎲 App version

Version 22.10.16+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
