### ISSUE TITLE
📚 Documentation: Booking status need to update on every step 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#302]
### 💭 Description 
1. On checkin booking status need to change fresh to Confirmed.
2. On check-out booking status need to change fresh to Checked_Out.
3. On pending booking status need to change fresh in to  Check_in_request
4. On cancel booking status need to change fresh in to  Cancelled By Customer
5. On cancel booking status need to change fresh in to  Cancelled_By_Hotel

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Rehachoudhary0** [comment]
1.On check-out booking status need to change fresh to Checked_Out.
2. On pending booking status need to change fresh in to Check_in_request both are pending in UI @rvndsngwn

**Comment by rvndsngwn** [comment]
done
