### ISSUE TITLE
🐛 Bug Report: hotel >Chat notification format

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#307]
### 👟 Reproduction steps

when the user sends a reception msg and hotel gets a notification format is not good as previous .

![Screenshot_20221107_165716](https://user-images.githubusercontent.com/85510636/200492556-9ad6d464-2958-43c4-bdb5-5a9f37cc065e.png)

### 👍 Expected behavior

it should be like this 👎 
New chat from Primary Traveler 
Mr. Hemant Kumar(#111), Room no. 100
Need extra pillows

### 👎 Actual Behavior

.

### ☎️ Log-in number

every hotel 

### 📲 User Type

Hotel

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
{"title":"New Chat From pandu ranga","body":"pandu ranga(#22), Room no. 800, h8

**Comment by parveen-malik** [comment]
done pls check

**Comment by Rehachoudhary0** [comment]
there is too much ,,,, commas and msg is not in new line pls need to correct ..looking not good if your getting confused with this ,then ols add Msg key front to message .

New chat from Primary Traveler
Mr. Hemant(#122), Room no. 100.
Msg:-Need extra pillows.


![Screenshot_20221110_124519](https://user-images.githubusercontent.com/85510636/201025024-7cd48e8b-a663-4e60-b097-96b26fd67484.png)
