### ISSUE TITLE
🐛 Bug Report: Hotel> food notification format not good 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#308]
### 👟 Reproduction steps

![Screenshot_20221108_130945](https://user-images.githubusercontent.com/85510636/200504657-2a289a75-ebd7-4e67-8374-1629e443ba32.png)

### 👍 Expected behavior

should be like this:- 
Food  Order  Received 
Mr. Reha Choudhary(#ARX988), Order ID.1
Room No. 100, Rs \-354

### 👎 Actual Behavior

.

### ☎️ Log-in number

for every hotel 

### 📲 User Type

Hotel

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
{"title":"New Food Order Received","body":" pandu ranga(#22) ,Order Id : 11\n Room no. : 800,, Rs \\- 177.00"

**Comment by parveen-malik** [comment]
order format applied............done pls check

**Comment by Rehachoudhary0** [comment]
This is also not according to format sir .pls check the format firstly .there is too much :::::::: pls add Room number and Rs add in new line . pls don't give all data in one like .its looks not good .
![Screenshot_20221110_131901](https://user-images.githubusercontent.com/85510636/201032287-bc8a2494-1185-4f23-bb63-22748e9a8c8e.png)

**Comment by parveen-malik** [comment]
$order_body_msg = ' '.$foodOrderBookedByName.'(#'.$CustomerId.'), '.'Order Id : ' . $orderId ."\n"." " . "Room No. ".$CheckinUserAssignedRoomNumbers." Rs \- " . $price_with_tax;
                    // 'Mr. Reha Choudhary(#ARX988), Order ID.1
                    // Room No. 100, Rs -354'
