### ISSUE TITLE
🐛 Bug Report: Traveler > Food order status format 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#309]
### 👟 Reproduction steps

Food order status users do not like good
![Screenshot_20221108_132137](https://user-images.githubusercontent.com/85510636/200506487-c06af81d-d4a9-4146-8ce2-ca06b8aba735.png)

### 👍 Expected behavior

should be like this .

Food  Order  Pending - Orio peace 
Mr. Reha Choudhary, Order ID.1
Rs \-354
### 👎 Actual Behavior

.

### ☎️ Log-in number

for every 

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
pls check and verify i not able to test.............modify booking
