### ISSUE TITLE
🐛 Bug Report: Travller >User not able to Check-In

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#310]
### 👟 Reproduction steps

user not able to check-In after scan hotel QR code showing blank screen 
![WhatsApp Image 2022-11-08 at 4 34 40 PM](https://user-images.githubusercontent.com/85510636/200554018-aec7721c-74e2-4190-98e0-9a1e5a078470.jpeg)

### 👍 Expected behavior

should be check_in

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
both user checkin through direct scan of same user in both versions of app old and new app.

checkin id 21 : get proper notifaication and chekin approval possible
checkin id 22 : get Blank screen and db request and Booking refrence added which is wrong when direct scan checkin
![image](https://user-images.githubusercontent.com/62441016/200803089-e2b698dc-3c8e-4ac6-a16a-346e15ccef25.png)
