### ISSUE TITLE
🐛 Bug Report: Hotel> Food updated is successfully but status not refreshing 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#313]
### 👟 Reproduction steps

when i changed the status of food hotel didn't go to backpage and home page or food list page not refreshing the status .

### 👍 Expected behavior

Should be working accordingly 

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Hotel

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
<img width="938" alt="Screenshot 2022-11-17 at 2 03 15 AM" src="https://user-images.githubusercontent.com/59143934/202288843-29a28f12-4bee-4824-b0bf-023920f04012.png">


When we change status of food from hotel/kitchen API throw the error but order status changed in background  https://app.roomi.stapp.com/api/hotel/order/statusUpdate

@Rehachoudhary0 @parveen-malik kindly check the issue.
