### ISSUE TITLE
🐛 Bug Report: Checkout User> last visit page review has to be updated when user give reviews to hotel .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#315]
### 👟 Reproduction steps

When user goes to give reviews to a hotel that time on last visit page  should be update when user gave reviews . need to refresh API on save button .
![Screenshot_20221118_172148](https://user-images.githubusercontent.com/85510636/202699566-861218fd-a0e2-4add-b655-d7cbb8659b1f.png)

### 👍 Expected behavior

Need to refresh API on save button .

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
