### ISSUE TITLE
🐛 Bug Report: Auto logout not working when 2 device has same number.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#316]
### 👟 Reproduction steps

Auto logout not working when two device has same number and the notification also does not get.

### 👍 Expected behavior

Auto logout working fine  when two devices has same number .notification should be getting on time.

### 👎 Actual Behavior

not working both issues. 

### ☎️ Log-in number

for all

### 📲 User Type

Hotel

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Firebase issue kindly connect to firebase team.
