### ISSUE TITLE
🐛 Bug Report: Hotel>Hotel home page chat list does not get refreshed 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#317]
### 👟 Reproduction steps

Hotel home page does not get refreshed when user send chat to hotel just gets notification.

### 👍 Expected behavior

should be working fine .

### 👎 Actual Behavior

.

### ☎️ Log-in number

all

### 📲 User Type

Hotel

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
done
