### ISSUE TITLE
🐛 Bug Report: User>Users get notifications on the status of food but there is no change on the Home Screen food list items

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#319]
### 👟 Reproduction steps

Users get notifications on the status of food but there is no change on the Home Screen food list items. Need to change the status update.

### 👍 Expected behavior

Need to change the status update.

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
invalid error not found
