### ISSUE TITLE
🐛 Bug Report:Hotel > Home page and food list page click on list showing error .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#325]
### 👟 Reproduction steps

https://user-images.githubusercontent.com/85510636/204509575-8271668f-36b7-471a-9f13-7cbc204e2185.mp4

### 👍 Expected behavior

should be working 

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Hotel

### 🎲 App version

Version 22.11.03+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Done
