### ISSUE TITLE
🐛 Bug Report: Hotel > chat text getting 2 times in chat page . 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#327]
### 👟 Reproduction steps

when hotel ay home page and get chat from user send one time massage like "Hello" after that hotel go to chat screen that massage reflect 2 times. when chat screen is open then doesn't get any issues  like that 
![WhatsApp Image 2022-12-08 at 3 57 05 PM](https://user-images.githubusercontent.com/85510636/206425240-40e57eae-b580-4b07-a71b-cecf2cafa92b.jpeg)

### 👍 Expected behavior

should be one time as sender sent .

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all 

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.08+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Done
