### ISSUE TITLE
🐛 Bug Report:  First launch  app shows home page after that shows login page ,only happening with android version 13

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#328]
### 👟 Reproduction steps

in user login firstly reflect home page don't know how this is visible for a sec after that showing error all below in this screen recording .

https://user-images.githubusercontent.com/85510636/206425901-c44ad03c-daf1-4e69-af94-5e3723f94d54.mp4

### 👍 Expected behavior

should be shows login page only and without any error .

### 👎 Actual Behavior

not working properly .

### ☎️ Log-in number

for all 

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.08+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Invalid bug not found

**Comment by Rehachoudhary0** [comment]
we got same issues again and again ... in first login app is show home page first not login page and there is showing errors .. 

https://user-images.githubusercontent.com/85510636/209912382-ceffe420-4aa8-4211-8d9d-2e8f723f94ff.mp4

**Comment by Rehachoudhary0** [comment]
now I have not gotten these types of issues. don't know how.
