### ISSUE TITLE
🐛 Bug Report: User > getting checkin notification but not showing after checkin page .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#329]
### 👟 Reproduction steps

 Getting checkin notification but not showing after checkin page . as showing in screen recording .

https://user-images.githubusercontent.com/85510636/206426970-dcfb75a3-6883-4870-8c58-ec961c3e9ade.mp4

### 👍 Expected behavior

should be working on time and get refreshed data . 

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.08+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Done
