### ISSUE TITLE
🐛 Bug Report: Hotel  > Home page showing delivered food as pending .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#330]
### 👟 Reproduction steps

pls watch the screen recording for a better understanding 

https://user-images.githubusercontent.com/85510636/206429654-b6a0bba0-9d27-4803-a6af-7a413ebc9cbf.mp4

https://user-images.githubusercontent.com/85510636/206429714-6c86d8ec-3a76-44d0-b33f-4b613b26cc24.mp4

### 👍 Expected behavior

should be accordingly 

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all 

### 📲 User Type

Admin

### 🎲 App version

Version 22.12.08+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
We did not call API again for this little thing since this item was recently in pending orders.
