### ISSUE TITLE
🐛 Bug Report: User/kitchen don't get any chat notification or chat .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#331]
### 👟 Reproduction steps

https://user-images.githubusercontent.com/85510636/206430629-e41f888d-5bd2-4680-a85c-4cd3e08373e4.mp4

### 👍 Expected behavior

should be working properly get notification and chat also 

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.08+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Firebase issue
