### ISSUE TITLE
🐛 Bug Report: User > not enable to registration 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#332]
### 👟 Reproduction steps

registration page showing this type of page 

![WhatsApp Image 2022-12-07 at 9 54 53 PM](https://user-images.githubusercontent.com/85510636/206432579-370a2760-bef9-4117-ba00-8153a65deac5.jpeg)

### 👍 Expected behavior

working as this is .

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all 

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.08+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Done
