### ISSUE TITLE
🐛 Bug Report: Hotel > Not able to switch another hotel getting error .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#333]
### 👟 Reproduction steps

https://user-images.githubusercontent.com/85510636/206637386-f9a493fa-12ed-481e-8adc-26579077dfd9.mp4

### 👍 Expected behavior

Need to switch hotel properly 

### 👎 Actual Behavior

not working switch hotel module

### ☎️ Log-in number

for all 

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.08+02

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
![Screenshot 2022-12-09 at 4 41 55 PM](https://user-images.githubusercontent.com/59143934/206689869-8cd1533e-5984-44ad-84f5-5b13e14e1375.png)
@parveen-malik sir kindly look into error.

**Comment by parveen-malik** [comment]
now ui recitfy by arvind sir..........now from both end this one is closed
