### ISSUE TITLE
🐛 Bug Report: Dashboard showing food order in pending but in the App there is no data for pending food.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#335]
### 👟 Reproduction steps

 Orio has 1 pending item but the dashboard of admin and hotel shows 2 food items pending.
![WhatsApp Image 2022-12-09 at 1 22 02 PM](https://user-images.githubusercontent.com/85510636/206656525-f0c7dd02-92e4-4731-91d9-36b550efae34.jpeg)
![WhatsApp Image 2022-12-09 at 1 23 47 PM](https://user-images.githubusercontent.com/85510636/206656536-fbc8159d-b87e-4851-9052-7b6827fc3ead.jpeg)

I found a pending list in dashboard not in-app in hotel podina hotel 
![WhatsApp Image 2022-12-09 at 11 41 01 AM](https://user-images.githubusercontent.com/85510636/206656165-9c8bf2f3-0cfa-4d82-b642-565fcf6cbe42.jpeg)
![WhatsApp Image 2022-12-09 at 11 41 09 AM](https://user-images.githubusercontent.com/85510636/206656174-78a8270a-964b-4cbe-8598-975cf55aa27e.jpeg)

### 👍 Expected behavior

According to API should be working in the APP and Dashboard.

### 👎 Actual Behavior

not actual according to API i think .. pls check this ..

### ☎️ Log-in number

7976436565 :-Orio peace 
8873739282 :-Hara Podina 

### 📲 User Type

Admin

### 🎲 App version

Version 22.12.08+02

### 💻 Operating system

Web

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
in dashboard food order shown all pending order and in app foodorder shown last 24 hours penind orders
