### ISSUE TITLE
🐛 Bug Report: Admin and particular hotel in back office shows booking for whole dates .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#336]
### 👟 Reproduction steps

in details of booking shows only one date of booking 29 number for all dates of hotel ..

![WhatsApp Image 2022-12-09 at 11 30 45 AM](https://user-images.githubusercontent.com/85510636/206657579-6b7cc84f-6612-43fb-9e4f-ef40fcfbe025.jpeg)
<img width="1440" alt="Screen Shot 2022-12-09 at 1 51 45 PM" src="https://user-images.githubusercontent.com/85510636/206657639-6632f3b5-dc19-49f3-a360-789a15eb5435.png">

### 👍 Expected behavior

when user books hotel  just then will show only booking.

### 👎 Actual Behavior

.

### ☎️ Log-in number

7976436565 :-Orio peace 

### 📲 User Type

Admin

### 🎲 App version

Version 22.12.08+02

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/207868898-322f6f87-de04-4328-85e9-8dfca5448afd.png)
