### ISSUE TITLE
🐛 Bug Report: User > registration data saved one time but user not able to go home page .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#339]
### 👟 Reproduction steps

Registration data saved one time but user not able to go home page but after second time of click this is going to be okk ... able to get home page .

### 👍 Expected behavior

It should be saved on first click then go to home page .

### 👎 Actual Behavior

.

### ☎️ Log-in number

all

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
Done
