### ISSUE TITLE
🐛 Bug Report:Hotel >Food status page > back press needed

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#341]
### 👟 Reproduction steps

When I am on food status page to change status of food after that I want to go back but back button is not working and home icone are also not working on that case so I need to click on service tab after that I had to click on home tab to go back on home page.

https://user-images.githubusercontent.com/85510636/208229062-c9edbf37-30f5-46e0-90e2-d900d2a87191.mp4

### 👍 Expected behavior

Should be working every function on tab on it 

### 👎 Actual Behavior

Not working properly 

### ☎️ Log-in number

For all hotel

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Rehachoudhary0** [comment]
@amitjangra01 pls this too

**Comment by amitjangra01** [comment]
debugging this one

**Comment by Rehachoudhary0** [comment]
if this is done by your side pls change the status of issues like ready ...

**Comment by Rehachoudhary0** [comment]
not working still .

**Comment by amitjangra01** [comment]
optimized code for this functionality.

**Comment by Rehachoudhary0** [comment]
not working still
