### ISSUE TITLE
🐛 Bug Report: Hotel > Home> unread symbol red dot showing after read chat

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#342]
### 👟 Reproduction steps

When hotel read the chat of traveler after that home page not showing unread dot on home page but after refresh home page this is showing again .

### 👍 Expected behavior

Should be working fine if all msg are read then don't need to show red dot .

### 👎 Actual Behavior

Not working fine 

### ☎️ Log-in number

All 

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.09+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
pls check @parveen-malik sir
https://app.roomistapp.com/api/hotel/chat/latest 
status provided by this api response doesn't change and always stays 'read' and also the unread count never sets to zero.
![Screenshot from 2022-12-17 13-51-20](https://user-images.githubusercontent.com/106227731/208232940-cb18907b-75c6-49cd-a02e-4a2519409623.png)

**Comment by amitjangra01** [comment]
Please check @parveen-malik sir
