### ISSUE TITLE
🐛 Bug Report: Hotel > customer details> room number not showing 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#343]
### 👟 Reproduction steps

Customer details not showing room number.

### 👍 Expected behavior

Hmm

### 👎 Actual Behavior

Not working 

### ☎️ Log-in number

All

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
api issue. kindly check @parveen-malik sir
![Screenshot from 2022-12-17 13-04-57](https://user-images.githubusercontent.com/106227731/208231383-a59becb3-13ed-40ec-a9a1-050c709209c2.png)

**Comment by Rehachoudhary0** [comment]
Yess @parveen-malik  sir pls check these issues.

**Comment by parveen-malik** [comment]
pls check its done

**Comment by amitjangra01** [comment]
issue resolved. data is not showing as null and room number is showing.

**Comment by Rehachoudhary0** [comment]
ok thanks
