### ISSUE TITLE
🐛 Bug Report: Hotel >Home page > Food list not going to refresh from directly home page.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#344]
### 👟 Reproduction steps

when we update food order from home page list directly click on food for update that will be not updated both side home page and particular food list page as shows in video ... that's why not able to logout .

https://user-images.githubusercontent.com/85510636/208419579-84fe2fe1-0523-4ec7-9ad3-df5060900c82.mp4

https://user-images.githubusercontent.com/85510636/208236771-eec8c49c-8837-478c-a637-a7992b16a803.mp4

### 👍 Expected behavior

should be refresh both side . Direcly and from food list page .

### 👎 Actual Behavior

not working directly home page .

### ☎️ Log-in number

for all

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
invalid

**Comment by Rehachoudhary0** [comment]
this is working ??
