### ISSUE TITLE
🐛 Bug Report: Travlere > After checked-In notification same time its not getting data of hotel 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#346]
### 👟 Reproduction steps

https://user-images.githubusercontent.com/85510636/208237897-b86e5e9d-8462-4800-87cb-0eb07f296ba6.mp4

### 👍 Expected behavior

.

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
invalid
