### ISSUE TITLE
🐛 Bug Report: Admin > QR scanner not working 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#347]
### 👟 Reproduction steps

when admin scan the QR code for assign the QR code to hotel this is showing blank page .

### 👍 Expected behavior

this is should be working fine 

### 👎 Actual Behavior

showing blank page 

### ☎️ Log-in number

all

### 📲 User Type

Admin

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
use single qr code while scanning @Rehachoudhary0 mam
