### ISSUE TITLE
🐛 Bug Report: Traveler>Chat issues.

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#348]
### 👟 Reproduction steps

need to view recorded video 

https://user-images.githubusercontent.com/85510636/208422700-add2e57a-d44d-4fac-b1cd-dc33b92e5393.mp4

### 👍 Expected behavior

working fully accordingly 

### 👎 Actual Behavior

not working rightt 

### ☎️ Log-in number

all

### 📲 User Type

Admin

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done
