### ISSUE TITLE
🐛 Bug Report: Traveler >Order details refresh issues 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#349]
### 👟 Reproduction steps

order has been delivered but showing pending in list .if there is in issues with API pls share the response with API name .

https://user-images.githubusercontent.com/85510636/208424670-34290844-df34-4a10-8510-5a584f54b6f9.mp4

### 👍 Expected behavior

according to status 

### 👎 Actual Behavior

not working for some food not for every .

### ☎️ Log-in number

all 

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done

**Comment by Rehachoudhary0** [comment]
still has same propblem .
