### ISSUE TITLE
🐛 Bug Report: travlere registration issues 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#350]
### 👟 Reproduction steps

not all time i got this only one time when a traveler registere

https://user-images.githubusercontent.com/85510636/208425676-392f8f10-f3fe-441a-a43b-52d0da6e2753.mp4

 then after save button showing blank screen.

### 👍 Expected behavior

i think something is not going right .

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
when i'll face the same then i'll check.

**Comment by Rehachoudhary0** [comment]
Still not working .. what kind of API giving u pls post here ..

https://user-images.githubusercontent.com/85510636/209925571-ef987dbc-23b6-4750-9958-999eb6686612.mp4
