### ISSUE TITLE
🐛 Bug Report: New Hotel has issues with profile layout 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#351]
### 👟 Reproduction steps

when admin(7876553248) create hotel after that login with these particular hotel (1412565656) showing UI is not accordingly . This hotel does not have inventory data but has profile data so it does not look like this .
![WhatsApp Image 2022-12-19 at 6 30 24 PM](https://user-images.githubusercontent.com/85510636/208431920-333e37e3-57e0-4c6f-995b-9b1dbaa61adb.jpeg)

### 👍 Expected behavior

Showing profile data proper manner.

### 👎 Actual Behavior

.

### ☎️ Log-in number

for without inventory hotel 

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done @Rehachoudhary0 mam
