### ISSUE TITLE
🐛 Bug Report: Admin >hotel list need to show hotel recent on top of list  and not able to search particular hotel .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#352]
### 👟 Reproduction steps

hotel list needs to show hotel recently on top of list. 

https://user-images.githubusercontent.com/85510636/208434773-94040c6f-2607-4339-9d65-c3ef033d35a7.mp4

### 👍 Expected behavior

.

### 👎 Actual Behavior

.

### ☎️ Log-in number

all

### 📲 User Type

Admin

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
recent hotel showing in top done and not able to search particular hotel is api issue @Rehachoudhary0  mam and please check @parveen-malik sir 
![Screenshot from 2022-12-19 22-32-33](https://user-images.githubusercontent.com/106227731/208488784-235bc066-3348-49a2-abb0-b8648fbb9627.png)

![Screenshot from 2022-12-19 22-33-20](https://user-images.githubusercontent.com/106227731/208488614-c0a0a777-870d-4220-9a8f-8f72af01a0ed.png)

for one search result api is giving multiple number of hotel results

**Comment by parveen-malik** [comment]
![image](https://user-images.githubusercontent.com/62441016/208591623-cec47d63-536e-4cfd-9a52-60fdcc8afb3a.png)

**Comment by parveen-malik** [comment]
pls @Rehachoudhary0
