### ISSUE TITLE
🐛 Bug Report: Hotel >Home page checking list UI overlapping 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#353]
### 👟 Reproduction steps

there is two data in list showing like this .. pls test whole app before sending to test .. 

![WhatsApp Image 2022-12-20 at 10 42 32 AM](https://user-images.githubusercontent.com/85510636/208588982-1288121a-f0c7-4afd-876b-a3a1bcea936f.jpeg)

### 👍 Expected behavior

should be looking good 

### 👎 Actual Behavior

overlapping layout 

### ☎️ Log-in number

for all hotel 

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done
