### ISSUE TITLE
🐛 Bug Report: Secondary Traveller > Home page not refresh on request Notification

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#356]
### 👟 Reproduction steps

when second traveller going to scan frist traveller to access hotel services then secondary traveller get notification after scan on that notification auto refresh is not working ..we have to pull home page to access all these .

### 👍 Expected behavior

need to auto refresh .

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all 

### 📲 User Type

Traveller - Secondary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done
