### ISSUE TITLE
🐛 Bug Report: HOtel > when hotel clock on pending request notification its redirect the hotel to booking page .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#357]
### 👟 Reproduction steps

when hotel click on pending request notification it redirect  to booking page not to pending check-in page .

### 👍 Expected behavior

it should be  redirect  to pending check-in page .

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done.
