### ISSUE TITLE
🐛 Bug Report: Hotel> not getting food reviews 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#358]
### 👟 Reproduction steps

Hotel not getting food reviews notification .

### 👍 Expected behavior

it should be getting on time .

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Hotel

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
not getting food reviews notification from backend.

**Comment by parveen-malik** [comment]
secoundery users gets notification of orderReview,OrderUpdate............done
