### ISSUE TITLE
🐛 Bug Report: Secondary user note getting notification 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#359]
### 👟 Reproduction steps

secondary user not getting notifications for chat and food status both .when hotel chat to traveler secondary user not getting . same as for when hotel change the status of food this is not getting ...

### 👍 Expected behavior

.

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Traveller - Secondary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by parveen-malik** [comment]
secoundery users gets notification of orderReview,OrderUpdate............done
