### ISSUE TITLE
🐛 Bug Report: Secondary user chat and order not clickable on right page 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#361]
### 👟 Reproduction steps

Secondary user chat not clickable on right page 

https://user-images.githubusercontent.com/85510636/210772359-749c6ba5-b10c-4968-8bbf-f091e94a2fd7.mp4

### 👍 Expected behavior

should be working like primary user 

### 👎 Actual Behavior

.

### ☎️ Log-in number

for all

### 📲 User Type

Traveller - Secondary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done
