### ISSUE TITLE
🚀 Feature: We need to call read API or read chat by hotel before checkout user .

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#362]
### 🔖 Feature description

We need to call read API or read chat by hotel before checkout user . if we doesn't apply this I will face the issues in count of chat according to @parveen-malik  sir ..

### 🎤 Pitch

if we doesn't apply this I will face the issues in count of chat according to @parveen-malik  sir ..

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
showed an info notice for unread messages and until the hotel read chat of that particular customer, hotel will not be able to check out him/her.

**Comment by parveen-malik** [comment]
done sir
