### ISSUE TITLE
🐛 Bug Report: Travler:-Today check-in (only visible today checkin by customers)

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#380]
### 👟 Reproduction steps

**Today check-in (only visible today checkin by customers)**

### 👍 Expected behavior

.

### 👎 Actual Behavior

Today check-in (only visible today checkin by customers)

### ☎️ Log-in number

.

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
date filter added for showing today checkins only
