### ISSUE TITLE
🚀 Feature:  Hotel :-Should view all open checkin where checkout is not done

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#381]
### 🔖 Feature description

A button (Open Check-in) should view all open checkin where checkout is not done.

### 🎤 Pitch

Need to know about all details of customer.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
already there
