### ISSUE TITLE
🚀 Feature: Hotel,Kitchen,Travller:-Food status should change via API to "delivered and datatime stamp",

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#382]
### 🔖 Feature description

At the time of food delivery, the customer accepts order and the food status should change via API to "delivered and datatime stamp", kitchen or reception should not change status of food order, only the customer and admin has access for it.

### 🎤 Pitch

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
food status update api integrated in user side where user will update the status of food to Delivered when food is recieved by him.
