### ISSUE TITLE
🚀 Feature: Kitchen:- A button at kitchen side - "Processing"

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#383]
### 🔖 Feature description

After food order there should a button at kitchen side - "Processing" so that customer notify for it.

### 🎤 Pitch

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
process button added
