### ISSUE TITLE
🚀 Feature:Hotel:- Id collection at the time of check-in

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#384]
### 🔖 Feature description

id collection at the time of check-in should visible on that screen, so that hotel will check what he is collected, or want to change it, then follow >>delete>> add again

### 🎤 Pitch

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done
