### ISSUE TITLE
🚀 Feature: Hotel :-view chats view bills on both green highlighted area

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#386]
### 🔖 Feature description

![WhatsApp Image 2024-01-17 at 7 05 03 PM](https://github.com/Rehachoudhary0/hotel_testing/assets/85510636/14fb23a5-b2d2-4daa-bb4d-243c8ecb5c32)
1. view chats
2. view bills
on both green highlighted area

### 🎤 Pitch

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
implemented
