### ISSUE TITLE
🐛 Bug Report: Travler :- Receiving button showing in pending status 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#388]
### 👟 Reproduction steps

![WhatsApp Image 2024-01-24 at 5 01 33 PM](https://github.com/Rehachoudhary0/hotel_testing/assets/85510636/a381b6de-c7a9-4d0f-a8a3-d648c35effc0)

### 👍 Expected behavior

receiving button should be changed to delivered and the look of a button not like button so we need to change color blue to green and change the shape according to button ..

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Traveller - Secondary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
fixed
