### ISSUE TITLE
🐛 Bug Report: Travller:-  Food order details should be like a bill format 

### ISSUE THREAD

**Issue by Rehachoudhary0** [Rehachoudhary0/hotel_testing#389]
### 👟 Reproduction steps

https://github.com/Rehachoudhary0/hotel_testing/assets/85510636/5be3bd47-9f2e-4943-afc7-58067b5db010

https://github.com/Rehachoudhary0/hotel_testing/assets/85510636/3e19c487-690f-4ede-9d5a-2cee4010d89a

according to the screen recording ... plz. update ..

### 👍 Expected behavior

.

### 👎 Actual Behavior

.

### ☎️ Log-in number

.

### 📲 User Type

Traveller - Primary

### 🎲 App version

Version 22.12.12+01

### 💻 Operating system

Android

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Rehachoudhary0/hotel_testing/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by amitjangra01** [comment]
done
